version: '3.3'

services:
  db:
    container_name: postgreSQL_container_messages
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: test2022
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    image: message:latest
    restart: on-failure
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=test2022
volumes:
  db:
    driver: local

